#!/usr/bin/env bash

set -euo pipefail

# Baseline injection runner (attack-case driven).
#
# Default behavior (recommended):
#   - Read <root>/attack_case.json (generated by web/exp/04)
#   - Inject a WASP baseline prompt into the configured breadcrumb path (default: /)
#     within the security_microtree when present
#   - Write <root>/static/*_injected.json and pack the injected static site
#
# This script does NOT generate attacker tasks (web/exp/04 owns that), and does NOT start the server unless requested.

PORT="${PORT:-8000}"
USE_SECURITY_MICROTREE="${USE_SECURITY_MICROTREE:-true}"
ATTACK_CASE="${ATTACK_CASE:-}"
BASELINE_INJECTION_FORMAT="${BASELINE_INJECTION_FORMAT:-}"
BASELINE_USER_GOAL_STR="${BASELINE_USER_GOAL_STR:-}"
BASELINE_USER_TASK_PATH="${BASELINE_USER_TASK_PATH:-}"
INJECT_PAGE_PATH="${INJECT_PAGE_PATH:-/}"

SERVE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --serve|--start-server)
      SERVE=1
      shift
      ;;
    *)
      echo "[web/baseline/run_injection] Warning: unknown arg $1 (ignored)" >&2
      shift
      ;;
  esac
done

if [[ -z "${BASELINE_INJECTION_FORMAT}" ]]; then
  echo "[web/baseline/run_injection] ERROR: BASELINE_INJECTION_FORMAT is required." >&2
  echo "[web/baseline/run_injection] Options: goal_hijacking_url_injection | goal_hijacking_plain_text | generic_url_injection | generic_plain_text" >&2
  exit 1
fi

BASE_ROOT="${EXPERIMENT_ROOT:-web/runs/trap_site_mvp}"
if [[ -n "${EXPERIMENT_ID:-}" ]]; then
  BASE_ROOT="${BASE_ROOT%/}/${EXPERIMENT_ID}"
fi
BASE_ROOT="${BASE_ROOT%/}"

if [[ -z "${ATTACK_CASE}" ]]; then
  ATTACK_CASE="${BASE_ROOT}/attack_case.json"
fi
if [[ ! -f "${ATTACK_CASE}" ]]; then
  echo "[web/baseline/run_injection] ERROR: attack_case.json not found: ${ATTACK_CASE}" >&2
  echo "[web/baseline/run_injection] Hint: generate it in web/exp/04 (e.g., make_security_attack_tasks.py or make_wasp_attack_tasks_from_manifest.py)." >&2
  exit 1
fi

USE_MICROTREE_FLAG=()
if [[ "${USE_SECURITY_MICROTREE}" == "false" ]]; then
  USE_MICROTREE_FLAG+=("--no-use-security-microtree")
fi

USER_GOAL_FLAG=()
if [[ -n "${BASELINE_USER_GOAL_STR}" ]]; then
  USER_GOAL_FLAG+=("--user-goal-str" "${BASELINE_USER_GOAL_STR}")
fi

USER_TASK_FLAG=()
if [[ -n "${BASELINE_USER_TASK_PATH}" ]]; then
  USER_TASK_FLAG+=("--user-task-path" "${BASELINE_USER_TASK_PATH}")
fi

echo "[web/baseline/run_injection] Step 1/2: injecting from attack_case=${ATTACK_CASE}"
python web/baseline/inject_from_attack_case.py \
  --experiment-root "${EXPERIMENT_ROOT:-web/runs/trap_site_mvp}" \
  ${EXPERIMENT_ID:+--experiment-id "${EXPERIMENT_ID}"} \
  --attack-case "${ATTACK_CASE}" \
  --injection-format "${BASELINE_INJECTION_FORMAT}" \
  --inject-page-path "${INJECT_PAGE_PATH}" \
  "${USE_MICROTREE_FLAG[@]}" \
  "${USER_GOAL_FLAG[@]}" \
  "${USER_TASK_FLAG[@]}"

echo "[web/baseline/run_injection] Step 2/2: packing injected static site"
python web/baseline/pack_injected_site.py \
  --experiment-root "${EXPERIMENT_ROOT:-web/runs/trap_site_mvp}" \
  ${EXPERIMENT_ID:+--experiment-id "${EXPERIMENT_ID}"}

if [[ "${SERVE}" == "1" ]]; then
  echo "[web/baseline/run_injection] Starting static server on port ${PORT}"
  bash web/exp/03_a2perf_render/start_server.sh "${PORT}"
fi
