#!/usr/bin/env bash

set -euo pipefail

# PSAA injection runner (attack-case driven).
#
# Default behavior (recommended):
#   - Read <root>/attack_case.json (generated by web/exp/04)
#   - Inject attacker intent into the merged site metadata (security_microtree when present)
#   - Write <root>/static/*_injected.json and pack injected static site
#
# This script does NOT generate attacker tasks (web/exp/04 owns that), and does NOT start the server unless requested.

PORT="${PORT:-8000}"
USE_SECURITY_MICROTREE="${USE_SECURITY_MICROTREE:-true}"
ATTACK_CASE="${ATTACK_CASE:-}"
PSAA_MODE="${PSAA_MODE:-dynamic}"
PSAA_VARIANT="${PSAA_VARIANT:-full}"
PSAA_PROMPT_SPEC="${PSAA_PROMPT_SPEC:-}"
PSAA_PROMPT_VERSION="${PSAA_PROMPT_VERSION:-base}"
INJECTION_GENERATION_LOG="${INJECTION_GENERATION_LOG:-}"

SERVE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --serve|--start-server)
      SERVE=1
      shift
      ;;
    *)
      echo "[run_injection] Warning: unknown arg $1 (ignored)" >&2
      shift
      ;;
  esac
done

BASE_ROOT="${EXPERIMENT_ROOT:-web/runs/trap_site_mvp}"
if [[ -n "${EXPERIMENT_ID:-}" ]]; then
  BASE_ROOT="${BASE_ROOT%/}/${EXPERIMENT_ID}"
fi
BASE_ROOT="${BASE_ROOT%/}"

if [[ -z "${ATTACK_CASE}" ]]; then
  ATTACK_CASE="${BASE_ROOT}/attack_case.json"
fi
if [[ ! -f "${ATTACK_CASE}" ]]; then
  echo "[run_injection] ERROR: attack_case.json not found: ${ATTACK_CASE}" >&2
  echo "[run_injection] Hint: generate it in web/exp/04 (e.g., make_security_attack_tasks.py or make_wasp_attack_tasks_from_manifest.py)." >&2
  exit 1
fi

INJECT_LOC=()
# Dynamic PSAA requires an externally provided injection start point.
# Prefer INJECT_START_*; fall back to legacy INJECT_PAGE_* for convenience.
if [[ -n "${INJECT_START_PAGE_INDEX:-}" ]]; then
  INJECT_LOC+=("--inject-start-page-index" "${INJECT_START_PAGE_INDEX}")
elif [[ -n "${INJECT_START_PAGE_PATH:-}" ]]; then
  INJECT_LOC+=("--inject-start-path" "${INJECT_START_PAGE_PATH}")
elif [[ -n "${INJECT_PAGE_INDEX:-}" ]]; then
  INJECT_LOC+=("--inject-start-page-index" "${INJECT_PAGE_INDEX}")
elif [[ -n "${INJECT_PAGE_PATH:-}" ]]; then
  INJECT_LOC+=("--inject-start-path" "${INJECT_PAGE_PATH}")
fi

if [[ "${PSAA_MODE}" == "dynamic" && ${#INJECT_LOC[@]} -eq 0 ]]; then
  echo "[run_injection] ERROR: PSAA_MODE=dynamic requires INJECT_START_PAGE_INDEX/INJECT_START_PAGE_PATH (or legacy INJECT_PAGE_INDEX/INJECT_PAGE_PATH)." >&2
  exit 1
fi

if [[ "${PSAA_MODE}" != "dynamic" ]]; then
  echo "[run_injection] ERROR: PSAA_MODE must be 'dynamic' (got: ${PSAA_MODE})." >&2
  exit 1
fi

case "${PSAA_VARIANT}" in
  full|wo_lure|wo_inertia|wo_payload)
    ;;
  *)
    echo "[run_injection] ERROR: unsupported PSAA_VARIANT='${PSAA_VARIANT}'." >&2
    echo "[run_injection] Allowed values: full | wo_lure | wo_inertia | wo_payload" >&2
    exit 1
    ;;
esac

INJECT_SCRIPT="web/psaa/inject_from_attack_case.py"
if [[ "${PSAA_VARIANT}" != "full" ]]; then
  INJECT_SCRIPT="web/psaa/ablation/inject_from_attack_case.py"
fi

USE_MICROTREE_FLAG=()
if [[ "${USE_SECURITY_MICROTREE}" == "false" ]]; then
  USE_MICROTREE_FLAG+=("--no-use-security-microtree")
fi

PROMPT_SPEC_FLAG=()
if [[ -n "${PSAA_PROMPT_SPEC}" ]]; then
  PROMPT_SPEC_FLAG+=("--prompt-spec" "${PSAA_PROMPT_SPEC}")
fi

PROMPT_VERSION_FLAG=()
if [[ -z "${PSAA_PROMPT_SPEC}" ]]; then
  PROMPT_VERSION_FLAG+=("--prompt-spec-version" "${PSAA_PROMPT_VERSION}")
fi

GEN_LOG_FLAG=()
if [[ -n "${INJECTION_GENERATION_LOG}" ]]; then
  GEN_LOG_FLAG+=("--generation-log" "${INJECTION_GENERATION_LOG}")
fi

# run (inject-only by default)
echo "[run_injection] Step 1/2: injecting from attack_case=${ATTACK_CASE}"
python "${INJECT_SCRIPT}" \
  --experiment-root "${EXPERIMENT_ROOT:-web/runs/trap_site_mvp}" \
  ${EXPERIMENT_ID:+--experiment-id "${EXPERIMENT_ID}"} \
  --attack-case "${ATTACK_CASE}" \
  --mode "${PSAA_MODE}" \
  --variant "${PSAA_VARIANT}" \
  "${USE_MICROTREE_FLAG[@]}" \
  "${PROMPT_SPEC_FLAG[@]}" \
  "${PROMPT_VERSION_FLAG[@]}" \
  "${GEN_LOG_FLAG[@]}" \
  "${INJECT_LOC[@]}"

echo "[run_injection] Step 2/2: packing injected static site"
python web/psaa/pack_injected_site.py \
  --experiment-root "${EXPERIMENT_ROOT:-web/runs/trap_site_mvp}" \
  ${EXPERIMENT_ID:+--experiment-id "${EXPERIMENT_ID}"}

if [[ "${SERVE}" == "1" ]]; then
  echo "[run_injection] Starting static server on port ${PORT}"
  bash web/exp/03_a2perf_render/start_server.sh "${PORT}"
fi
